[build]
builder = "NIXPACKS"
nixpacksPlan = "nodejs"
buildCommand = "cd Backend && npm install && npx prisma generate"

[deploy]
startCommand = "cd Backend && node src/server.js"
restartPolicyType = "ON_FAILURE"