const { Router } = require('express')
const userRoutes = require('../modules/users/user.routes')
const estudianteRoutes = require('../modules/estudiantes/estudiante.routes')
const authRoutes = require('../modules/auth/auth.routes')
const dashboardRoutes = require('../modules/dashboard/dashboard.routes')
const reservaRoutes = require('../modules/reservas/reserva.routes')
const asistenciaRoutes = require('../modules/asistencia/asistencia.routes')
const turnoRoutes = require('../modules/turnos/turno.routes')
const estadisticasRoutes = require('../modules/estadisticas/estadisticas.routes')
const inscripcionRoutes = require('../modules/inscripciones/inscripcion.routes')
const configuracionRoutes = require('../modules/configuracion/configuracion.routes')
const pagoRoutes = require('../modules/pagos/pago.routes')
const soporteRoutes = require('../modules/soporte/soporte.routes')
const resenaRoutes = require('../modules/resenas/resena.routes')
const menuRoutes = require('../modules/menu/menu.routes')
const qrRoutes = require('../modules/qr/qr.routes')
const biometriaRoutes = require('../modules/biometria/biometria.routes')

const router = Router()

router.use('/auth', authRoutes)
router.use('/users', userRoutes)
router.use('/estudiantes', estudianteRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/reservas', reservaRoutes)
router.use('/asistencia', asistenciaRoutes)
router.use('/turnos', turnoRoutes)
router.use('/estadisticas', estadisticasRoutes)
router.use('/inscripciones', inscripcionRoutes)
router.use('/configuracion-formulario', configuracionRoutes)
router.use('/pagos', pagoRoutes)
router.use('/soporte', soporteRoutes)
router.use('/resenas', resenaRoutes)
router.use('/menu', menuRoutes)
router.use('/qr', qrRoutes)
router.use('/huellas', biometriaRoutes)

module.exports = router