const { Router } = require('express')
const userRoutes = require('./user.routes')
const estudianteRoutes = require('./estudiante.routes')
const authRoutes = require('./auth.routes')
const dashboardRoutes = require('./dashboard.routes')
const reservaRoutes = require('./reserva.routes')
const asistenciaRoutes = require('./asistencia.routes')
const turnoRoutes = require('./turno.routes')
const estadisticasRoutes = require('./estadisticas.routes')
const inscripcionRoutes = require('./inscripcion.routes')
const configuracionRoutes = require('./configuracion.routes')
const pagoRoutes = require('./pago.routes')
const soporteRoutes = require('./soporte.routes')
const resenaRoutes = require('./resena.routes')
const menuRoutes = require('./menu.routes')
const qrRoutes = require('./qr.routes')
const biometriaRoutes = require('./biometria.routes')
const notificacionRoutes = require('./notificacion.routes')

const router = Router()

router.use('/auth', authRoutes)
router.use('/users', userRoutes)
router.use('/estudiantes', estudianteRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/reservas', reservaRoutes)
router.use('/asistencia', asistenciaRoutes)
router.use('/turnos', turnoRoutes)
router.use('/estadisticas', estadisticasRoutes)
router.use('/inscripciones', inscripcionRoutes)
router.use('/configuracion-formulario', configuracionRoutes)
router.use('/pagos', pagoRoutes)
router.use('/soporte', soporteRoutes)
router.use('/resenas', resenaRoutes)
router.use('/menu', menuRoutes)
router.use('/qr', qrRoutes)
router.use('/biometria', biometriaRoutes)
router.use('/huellas', biometriaRoutes)
router.use('/notificaciones', notificacionRoutes)

module.exports = router